modLoader="javafml"
loaderVersion="[43,)"
license="GNU General Public License version 3 (GPLv3)"

[[mods]]
modId="omnipotentcraftingtable"
version="1.0.0"
displayName="OmnipotentCraftingTable"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="FuBangkun"
description='''
Enables the crafting table to make recipes for other squares.
'''

[[dependencies.omnipotentcraftingtable]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2]"
    ordering="NONE"
    side="BOTH"




